[package]
name = "rs9"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
calamine = "0.18.0"
num = "0.4.0"
image = "0.24.1"
imageproc = "0.23.0"
rusttype = "0.9.2"

